---
- name: Download archive
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-arm64.tar.gz
    checksum: sha256:https://get.helm.sh/helm-{{ helm_version }}-linux-arm64.tar.gz.sha256sum
    dest: /tmp
    owner: root
    group: root
    mode: "644"

- name: Install binary
  ansible.builtin.unarchive:
    src: /tmp/helm-{{ helm_version }}-linux-arm64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: "755"
    remote_src: true

- name: Delete archive
  ansible.builtin.file:
    path: /tmp/helm-{{ helm_version }}-linux-arm64.tar.gz
    state: absent
